spring.application.name=refund-cancel

spring.rabbitmq.publisher-confirm-type=correlated

spring.datasource.url=jdbc:postgresql://localhost:5432/payments
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# TRACING (Micrometer + OTLP)
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.otlp.metrics.export.enabled=true

# ESSENCIAL (Jaeger service name)
otel.service.name=refund-cancel
